from django.db import models
from django.core.validators import MinValueValidator 
from django.contrib.auth.models import User

# Create your models here.


class Customer(models.Model):
    # use automatic custID generated by django as PK
    user = models.OneToOneField(User, on_delete = models.CASCADE,null = True, blank=True)
    customer_name = models.CharField(max_length=100)
    customer_address = models.TextField()

    def __str__(self):
        return self.customer_name

class CustomerProfile(models.Model): 
    #1 to 1 relationship
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE, primary_key=True)

    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]

    EMPLOYMENT_STATUS_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Self-employed', 'Self-employed'),
        ('Student', 'Student'),
        ('Retired', 'Retired'),
    ]

    OCCUPATION_CHOICES = [
        ('Admin', 'Admin'),
        ('Education', 'Education'),
        ('Sales', 'Sales'),
        ('Service', 'Service'),
        ('Skilled Trades', 'Skilled Trades'),
        ('Tech', 'Tech'),
    ]

    EDUCATION_CHOICES = [
        ('Secondary', 'Secondary'),
        ('Diploma', 'Diploma'),
        ('Bachelor', 'Bachelor'),
        ('Master', 'Master'),
        ('Doctorate', 'Doctorate'),
    ]
    
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    employment_status = models.CharField(max_length=50, choices=EMPLOYMENT_STATUS_CHOICES, null=True, blank=True)
    occupation = models.CharField(max_length=50, choices=OCCUPATION_CHOICES, null=True, blank=True)
    education = models.CharField(max_length=50, choices=EDUCATION_CHOICES, null=True, blank=True)
    household_size = models.IntegerField(null=True, blank=True)
    has_children = models.BooleanField(default=False)
    monthly_income = models.IntegerField(null=True, blank=True) 

    def __str__(self):
        return f"Profile of {self.customer.customer_name}"

class Category(models.Model):
    # use automatic categID generated by django as PK
    category_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.category_name

class Subcategory(models.Model):
    # use automatic subcatID generated by django as PK
    # 1 to many relationship
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    subcategory_name = models.CharField(max_length=100)

    class Meta:
        unique_together = ('category', 'subcategory_name') 

    def __str__(self):
        return f"{self.category.category_name} - {self.subcategory_name}"

class Product(models.Model):
    sku_code = models.CharField(max_length=150, primary_key=True, db_index=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT) # PROTECT prevents category deletion if products exist
    subcategory = models.ForeignKey(Subcategory, on_delete=models.PROTECT) 

    product_name = models.CharField(max_length=200)
    product_description = models.TextField(blank=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    product_rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    quantity_on_hand = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    reorder_quantity = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name

class Order(models.Model):
    order_number = models.CharField(max_length=9, primary_key=True, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    order_date_time = models.DateTimeField(auto_now_add=True)
    ORDER_STATUS_CHOICES = [
        ('Processing', 'Processing'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
    ]
    order_status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='Processing')
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"Order {self.order_number} by {self.customer.customer_name}"

class OrderItem(models.Model):
    # use automatic orderItemID generated by django as PK
    order = models.ForeignKey(Order, on_delete=models.CASCADE, to_field='order_number')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, to_field='sku_code')
    purchased_price = models.DecimalField( #ensures price of sold products does not change upon price update later on
        max_digits=10, 
        decimal_places=2, 
        validators=[MinValueValidator(0)],
    )
    quantity = models.IntegerField(validators=[MinValueValidator(1)])
    line_subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity}x {self.product.product_name} in Order {self.order.order_number}"

    class Meta:
        unique_together = ('order', 'product')