# Generated by Django 5.2.7 on 2025-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Education', 'Education'), ('Sales', 'Sales'), ('Service', 'Service'), ('Skilled Trades', 'Skilled Trades'), ('Tech', 'Tech')], max_length=50, null=True),
        ),
    ]
