# Generated by Django 5.2.7 on 2025-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='monthly_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
