# Generated by Django 5.2.7 on 2025-10-28 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_alter_customerprofile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchased_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
