# Generated by Django 5.2.7 on 2025-10-28 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0003_orderitem_purchased_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
